name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies using Bundler
      - name: Install Jekyll dependencies
        run: |
          bundle install

      # Build the Jekyll site
      - name: Build Jekyll site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
